# Generated by Django 3.2.3 on 2021-09-23 04:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210923_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
